/**
 * SillyTavern DB/Memory Extension - Full Integration Version
 * Implements complete long-term memory flow
 */

// Global state for the extension
const dbMemoryState = {
    connected: false,
    backendUrl: '',
    username: '',
    password: '',
    jwtToken: null,
    tokenExpiry: null,
    settings: {
        autoSync: true,
        messagesPerSync: 10,
        memoriesPerContext: 5,
        similarityThreshold: 0.7,
        enableAutoExtraction: true,
        showRelevanceScores: true,
        debugMode: false
    },
    lastProcessedMessageId: null,
    processingQueue: [],
    isProcessing: false
};

// Load saved settings
function loadSettings() {
    const saved = localStorage.getItem('db_memory_settings');
    if (saved) {
        try {
            const parsed = JSON.parse(saved);
            Object.assign(dbMemoryState, parsed);
        } catch (e) {
            console.error('[DB Memory] Failed to load settings:', e);
        }
    }
}

// Save settings
function saveSettings() {
    localStorage.setItem('db_memory_settings', JSON.stringify(dbMemoryState));
}

// HTTP Client with JWT
async function apiCall(endpoint, options = {}) {
    const url = `${dbMemoryState.backendUrl}${endpoint}`;
    const headers = {
        'Content-Type': 'application/json',
        ...(dbMemoryState.jwtToken ? { 'Authorization': `Bearer ${dbMemoryState.jwtToken}` } : {})
    };
    
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000);
    
    try {
        const response = await fetch(url, {
            ...options,
            headers: { ...headers, ...options.headers },
            signal: controller.signal
        });
        
        clearTimeout(timeoutId);
        
        if (response.status === 401 && dbMemoryState.jwtToken) {
            // Token expired, try to re-authenticate
            await authenticate();
            return apiCall(endpoint, options);
        }
        
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${await response.text()}`);
        }
        
        return response.status === 204 ? null : await response.json();
    } catch (error) {
        clearTimeout(timeoutId);
        if (error.name === 'AbortError') {
            throw new Error('Request timeout');
        }
        throw error;
    }
}

// Authentication
async function authenticate() {
    if (!dbMemoryState.username || !dbMemoryState.password) {
        throw new Error('No credentials provided');
    }
    
    const response = await apiCall('/api/auth/login', {
        method: 'POST',
        body: JSON.stringify({
            username: dbMemoryState.username,
            password: dbMemoryState.password
        })
    });
    
    if (response && response.token) {
        dbMemoryState.jwtToken = response.token;
        // Parse expiry from JWT payload
        try {
            const payload = JSON.parse(atob(response.token.split('.')[1]));
            dbMemoryState.tokenExpiry = new Date(payload.exp * 1000).toISOString();
        } catch (e) {
            console.warn('[DB Memory] Could not parse token expiry:', e);
        }
        dbMemoryState.connected = true;
        saveSettings();
        updateConnectionStatus();
        return true;
    }
    
    throw new Error('Authentication failed');
}

// Health check
async function testConnection() {
    try {
        const response = await apiCall('/health');
        return response && response.status === 'ok';
    } catch (error) {
        console.error('[DB Memory] Health check failed:', error);
        return false;
    }
}

// Process a message through memory engine
async function processMessage(message, role = 'user') {
    if (!dbMemoryState.connected) {
        throw new Error('Not connected to backend');
    }
    
    const context = getContext();
    const chatId = context.chatId;
    const characterId = context.characterId;
    
    const response = await apiCall('/api/memories/process', {
        method: 'POST',
        body: JSON.stringify({
            content: message,
            role: role,
            chatId: chatId || null,
            characterId: characterId || null,
            sourceMessageId: null // Will be generated by backend
        })
    });
    
    return response;
}

// Build context for generation
async function buildContext(query) {
    if (!dbMemoryState.connected) {
        throw new Error('Not connected to backend');
    }
    
    const context = getContext();
    const chatId = context.chatId;
    const characterId = context.characterId;
    
    const response = await apiCall('/api/context', {
        method: 'POST',
        body: JSON.stringify({
            query: query,
            chatId: chatId || null,
            characterId: characterId || null,
            types: [],
            memoryLimit: dbMemoryState.settings.memoriesPerContext,
            messageLimit: dbMemoryState.settings.messagesPerSync,
            similarityThreshold: dbMemoryState.settings.similarityThreshold
        })
    });
    
    return response;
}

// Save message to backend
async function saveMessage(content, role = 'user') {
    if (!dbMemoryState.connected) {
        throw new Error('Not connected to backend');
    }
    
    const context = getContext();
    const chatId = context.chatId;
    
    if (!chatId) {
        throw new Error('No active chat');
    }
    
    const response = await apiCall('/api/messages', {
        method: 'POST',
        body: JSON.stringify({
            chatId: chatId,
            role: role,
            content: content
        })
    });
    
    return response;
}

// Update connection status display
function updateConnectionStatus() {
    const statusEl = $('#db_memory_status');
    if (!statusEl.length) return;
    
    if (dbMemoryState.connected) {
        statusEl.text('Connected').css({ background: '#d4edda', color: '#155724' });
    } else {
        statusEl.text('Disconnected').css({ background: '#f8d7da', color: '#721c24' });
    }
}

// Show status message
function showStatus(message, type = 'info') {
    const statusEl = $('#db_memory_status_msg');
    if (!statusEl.length) return;
    
    const colors = {
        success: { bg: '#d4edda', color: '#155724' },
        error: { bg: '#f8d7da', color: '#721c24' },
        info: { bg: '#d1ecf1', color: '#0c5460' }
    };
    
    const color = colors[type] || colors.info;
    statusEl.text(message).css(color).show();
    
    setTimeout(() => statusEl.fadeOut(), 3000);
}

// Initialize extension
function initializeExtensionUI() {
    const uiHTML = `
        <div id="db_memory_extension_panel" class="inline-drawer">
            <div class="inline-drawer-toggle inline-drawer-header">
                <b>DB Memory Extension</b>
                <div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div>
            </div>
            <div class="inline-drawer-content">
                
                <div style="margin-bottom: 15px;">
                    <h4 style="margin: 10px 0 5px 0;">Backend Connection</h4>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_backend_url" style="display: block; margin-bottom: 5px;">Backend URL:</label>
                        <input type="text" id="db_memory_backend_url" style="width: 100%; padding: 8px; margin-bottom: 10px;" placeholder="http://10.134.209.9:3000">
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_username" style="display: block; margin-bottom: 5px;">Username:</label>
                        <input type="text" id="db_memory_username" style="width: 100%; padding: 8px; margin-bottom: 10px;" placeholder="test_user">
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_password" style="display: block; margin-bottom: 5px;">Password:</label>
                        <input type="password" id="db_memory_password" style="width: 100%; padding: 8px; margin-bottom: 10px;" placeholder="testpass123">
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <button id="db_memory_connect_btn" style="padding: 8px 15px; margin-right: 10px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer;">Connect</button>
                        <button id="db_memory_test_btn" style="padding: 8px 15px; background: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer;">Test</button>
                        <button id="db_memory_disconnect_btn" style="padding: 8px 15px; background: #dc3545; color: white; border: none; border-radius: 4px; cursor: pointer;">Disconnect</button>
                    </div>
                    
                    <div id="db_memory_status" style="padding: 8px; margin-top: 5px; border-radius: 4px; font-weight: bold;">Disconnected</div>
                    <div id="db_memory_status_msg" style="padding: 8px; margin-top: 5px; border-radius: 4px; display: none;"></div>
                </div>
                
                <div style="margin-bottom: 15px;">
                    <h4 style="margin: 10px 0 5px 0;">Auto-Sync Settings</h4>
                    
                    <div style="margin-bottom: 10px;">
                        <label>
                            <input type="checkbox" id="db_memory_auto_sync"> Auto-sync messages to database
                        </label>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label>
                            <input type="checkbox" id="db_memory_auto_extraction"> Auto-extract memories from messages
                        </label>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_messages_per_sync" style="display: block; margin-bottom: 5px;">Messages per sync:</label>
                        <input type="number" id="db_memory_messages_per_sync" style="width: 100px; padding: 5px;" min="1" max="50" value="10">
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_memories_per_context" style="display: block; margin-bottom: 5px;">Memories per context:</label>
                        <input type="number" id="db_memory_memories_per_context" style="width: 100px; padding: 5px;" min="1" max="20" value="5">
                    </div>
                </div>
                
                <div style="margin-bottom: 15px;">
                    <h4 style="margin: 10px 0 5px 0;">Context Settings</h4>
                    
                    <div style="margin-bottom: 10px;">
                        <label for="db_memory_similarity_threshold" style="display: block; margin-bottom: 5px;">
                            Similarity threshold: <span id="db_memory_threshold_value">0.7</span>
                        </label>
                        <input type="range" id="db_memory_similarity_threshold" style="width: 100%;" min="0" max="1" step="0.01" value="0.7">
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <label>
                            <input type="checkbox" id="db_memory_show_scores"> Show relevance scores
                        </label>
                    </div>
                </div>
                
                <div style="margin-bottom: 15px;">
                    <h4 style="margin: 10px 0 5px 0;">Manual Operations</h4>
                    
                    <div style="margin-bottom: 10px;">
                        <button id="db_memory_build_context_btn" style="padding: 8px 15px; background: #17a2b8; color: white; border: none; border-radius: 4px; cursor: pointer;">Build Context</button>
                        <button id="db_memory_process_last_msg_btn" style="padding: 8px 15px; background: #ffc107; color: black; border: none; border-radius: 4px; cursor: pointer;">Process Last Message</button>
                    </div>
                </div>
                
                <div style="margin-bottom: 15px;">
                    <h4 style="margin: 10px 0 5px 0;">Debug</h4>
                    
                    <div style="margin-bottom: 10px;">
                        <label>
                            <input type="checkbox" id="db_memory_debug_mode"> Debug mode
                        </label>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <button id="db_memory_save_settings" style="padding: 8px 15px; background: #28a745; color: white; border: none; border-radius: 4px; cursor: pointer;">Save Settings</button>
                        <button id="db_memory_reset_settings" style="padding: 8px 15px; background: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;">Reset Settings</button>
                    </div>
                </div>
                
            </div>
        </div>
    `;
    
    $('#extensions_settings2').append(uiHTML);
    
    // Load saved settings
    loadSettings();
    populateSettings();
    
    // Bind events
    $('#db_memory_connect_btn').on('click', handleConnect);
    $('#db_memory_test_btn').on('click', handleTest);
    $('#db_memory_disconnect_btn').on('click', handleDisconnect);
    $('#db_memory_build_context_btn').on('click', handleBuildContext);
    $('#db_memory_process_last_msg_btn').on('click', handleProcessLastMessage);
    $('#db_memory_save_settings').on('click', handleSaveSettings);
    $('#db_memory_reset_settings').on('click', handleResetSettings);
    $('#db_memory_similarity_threshold').on('input', function() {
        $('#db_memory_threshold_value').text(parseFloat(this.value).toFixed(2));
    });
    
    updateConnectionStatus();
}

// Populate settings from state
function populateSettings() {
    $('#db_memory_backend_url').val(dbMemoryState.backendUrl);
    $('#db_memory_username').val(dbMemoryState.username);
    $('#db_memory_auto_sync').prop('checked', dbMemoryState.settings.autoSync);
    $('#db_memory_auto_extraction').prop('checked', dbMemoryState.settings.enableAutoExtraction);
    $('#db_memory_messages_per_sync').val(dbMemoryState.settings.messagesPerSync);
    $('#db_memory_memories_per_context').val(dbMemoryState.settings.memoriesPerContext);
    $('#db_memory_similarity_threshold').val(dbMemoryState.settings.similarityThreshold);
    $('#db_memory_show_scores').prop('checked', dbMemoryState.settings.showRelevanceScores);
    $('#db_memory_debug_mode').prop('checked', dbMemoryState.settings.debugMode);
    $('#db_memory_threshold_value').text(dbMemoryState.settings.similarityThreshold.toFixed(2));
}

// Handle connect
async function handleConnect() {
    const url = $('#db_memory_backend_url').val().trim();
    const user = $('#db_memory_username').val().trim();
    const pass = $('#db_memory_password').val();
    
    if (!url || !user || !pass) {
        showStatus('Please fill all fields', 'error');
        return;
    }
    
    dbMemoryState.backendUrl = url;
    dbMemoryState.username = user;
    dbMemoryState.password = pass;
    
    showStatus('Connecting...', 'info');
    
    try {
        await authenticate();
        showStatus('Connected successfully!', 'success');
    } catch (error) {
        dbMemoryState.connected = false;
        updateConnectionStatus();
        showStatus(`Connection failed: ${error.message}`, 'error');
    }
}

// Handle test
async function handleTest() {
    if (!dbMemoryState.backendUrl) {
        showStatus('Please enter backend URL', 'error');
        return;
    }
    
    showStatus('Testing connection...', 'info');
    
    try {
        const isHealthy = await testConnection();
        if (isHealthy) {
            showStatus('Backend is healthy', 'success');
        } else {
            showStatus('Backend not responding', 'error');
        }
    } catch (error) {
        showStatus(`Test failed: ${error.message}`, 'error');
    }
}

// Handle disconnect
function handleDisconnect() {
    dbMemoryState.connected = false;
    dbMemoryState.jwtToken = null;
    dbMemoryState.tokenExpiry = null;
    dbMemoryState.password = '';
    saveSettings();
    updateConnectionStatus();
    showStatus('Disconnected', 'info');
}

// Handle build context
async function handleBuildContext() {
    if (!dbMemoryState.connected) {
        showStatus('Not connected to backend', 'error');
        return;
    }
    
    const context = getContext();
    if (!context.chat || context.chat.length === 0) {
        showStatus('No messages in current chat', 'error');
        return;
    }
    
    showStatus('Building context...', 'info');
    
    try {
        const lastMessage = context.chat[context.chat.length - 1];
        const query = lastMessage.mes || lastMessage.message || 'Latest chat context';
        
        const result = await buildContext(query);
        console.log('[DB Memory] Context result:', result);
        showStatus(`Context built: ${result.entries.length} memories found`, 'success');
    } catch (error) {
        showStatus(`Context build failed: ${error.message}`, 'error');
    }
}

// Handle process last message
async function handleProcessLastMessage() {
    if (!dbMemoryState.connected) {
        showStatus('Not connected to backend', 'error');
        return;
    }
    
    const context = getContext();
    if (!context.chat || context.chat.length === 0) {
        showStatus('No messages in current chat', 'error');
        return;
    }
    
    showStatus('Processing last message...', 'info');
    
    try {
        const lastMessage = context.chat[context.chat.length - 1];
        const content = lastMessage.mes || lastMessage.message || '';
        const role = lastMessage.is_user ? 'user' : 'assistant';
        
        if (!content) {
            showStatus('Last message has no content', 'error');
            return;
        }
        
        const result = await processMessage(content, role);
        console.log('[DB Memory] Process result:', result);
        showStatus(`Message processed: ${result.candidates.length} candidates, ${result.created.length} created`, 'success');
    } catch (error) {
        showStatus(`Message processing failed: ${error.message}`, 'error');
    }
}

// Handle save settings
function handleSaveSettings() {
    dbMemoryState.backendUrl = $('#db_memory_backend_url').val().trim();
    dbMemoryState.username = $('#db_memory_username').val().trim();
    dbMemoryState.settings.autoSync = $('#db_memory_auto_sync').prop('checked');
    dbMemoryState.settings.enableAutoExtraction = $('#db_memory_auto_extraction').prop('checked');
    dbMemoryState.settings.messagesPerSync = parseInt($('#db_memory_messages_per_sync').val()) || 10;
    dbMemoryState.settings.memoriesPerContext = parseInt($('#db_memory_memories_per_context').val()) || 5;
    dbMemoryState.settings.similarityThreshold = parseFloat($('#db_memory_similarity_threshold').val()) || 0.7;
    dbMemoryState.settings.showRelevanceScores = $('#db_memory_show_scores').prop('checked');
    dbMemoryState.settings.debugMode = $('#db_memory_debug_mode').prop('checked');
    
    saveSettings();
    showStatus('Settings saved', 'success');
}

// Handle reset settings
function handleResetSettings() {
    if (!confirm('Reset all settings to defaults?')) return;
    
    dbMemoryState.backendUrl = '';
    dbMemoryState.username = '';
    dbMemoryState.password = '';
    dbMemoryState.settings = {
        autoSync: true,
        messagesPerSync: 10,
        memoriesPerContext: 5,
        similarityThreshold: 0.7,
        enableAutoExtraction: true,
        showRelevanceScores: true,
        debugMode: false
    };
    
    populateSettings();
    saveSettings();
    showStatus('Settings reset to defaults', 'info');
}

// Hook into SillyTavern message flow
function hookIntoMessageFlow() {
    // Listen for new messages being added to chat
    $(document).on('click', '#send_form button, #Regenerate, #Continue', function() {
        if (!dbMemoryState.connected || !dbMemoryState.settings.autoSync) return;
        
        setTimeout(async () => {
            try {
                const context = getContext();
                if (!context.chat || context.chat.length === 0) return;
                
                const lastMessage = context.chat[context.chat.length - 1];
                if (!lastMessage.mes && !lastMessage.message) return;
                
                const content = lastMessage.mes || lastMessage.message;
                const role = lastMessage.is_user ? 'user' : 'assistant';
                
                // Save message to backend
                await saveMessage(content, role);
                
                // Process for memory extraction if enabled
                if (dbMemoryState.settings.enableAutoExtraction) {
                    await processMessage(content, role);
                }
                
                if (dbMemoryState.settings.debugMode) {
                    console.log('[DB Memory] Saved message to backend:', { content, role });
                }
            } catch (error) {
                if (dbMemoryState.settings.debugMode) {
                    console.error('[DB Memory] Error saving message:', error);
                }
            }
        }, 1000); // Wait for message to be processed
    });
    
    // Hook into character response generation
    $(document).on('click', '#Regenerate, #Continue', function() {
        if (!dbMemoryState.connected || !dbMemoryState.settings.autoSync) return;
        
        setTimeout(async () => {
            try {
                const context = getContext();
                if (!context.chat || context.chat.length === 0) return;
                
                // Find the last character response
                let lastCharResponse = null;
                for (let i = context.chat.length - 1; i >= 0; i--) {
                    const msg = context.chat[i];
                    if (!msg.is_user && (msg.mes || msg.message)) {
                        lastCharResponse = msg;
                        break;
                    }
                }
                
                if (lastCharResponse) {
                    const content = lastCharResponse.mes || lastCharResponse.message;
                    // Process character response for memory extraction
                    await processMessage(content, 'assistant');
                    
                    if (dbMemoryState.settings.debugMode) {
                        console.log('[DB Memory] Processed character response:', content.substring(0, 50) + '...');
                    }
                }
            } catch (error) {
                if (dbMemoryState.settings.debugMode) {
                    console.error('[DB Memory] Error processing character response:', error);
                }
            }
        }, 2000); // Wait for response to be generated
    });
}

// Initialize when document is ready
$(document).ready(function() {
    console.log('[DB Memory] Extension initializing...');
    
    // Check if we're in extension settings area
    const settingsContainer = $('#extensions_settings2');
    if (settingsContainer.length > 0) {
        initializeExtensionUI();
    }
    
    // Hook into message flow
    hookIntoMessageFlow();
    
    // Try to auto-connect if we have credentials
    loadSettings();
    if (dbMemoryState.backendUrl && dbMemoryState.username && dbMemoryState.password) {
        if (dbMemoryState.jwtToken && dbMemoryState.tokenExpiry) {
            const now = new Date();
            const expiry = new Date(dbMemoryState.tokenExpiry);
            if (now < expiry) {
                // Token is still valid
                dbMemoryState.connected = true;
                updateConnectionStatus();
            } else {
                // Token expired, try to re-authenticate
                authenticate().catch(() => {
                    console.warn('[DB Memory] Auto-auth failed, staying disconnected');
                });
            }
        } else {
            // No token, need to authenticate
            authenticate().catch(() => {
                console.warn('[DB Memory] Auto-auth failed, staying disconnected');
            });
        }
    }
    
    console.log('[DB Memory] Extension initialized');
});